### ISSUE TITLE
OpenMVS : Error 

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#8] opened 2015-12-13 23:13 UTC
Hi Pierre-Yves,

Hope you spent a nice week-end! I just tested to install openMVS, however because it is in testing I was not sure, it is relevant to report it, but just in case ...

```
CMakeFiles/InterfaceOpenMVG.dir/InterfaceOpenMVG.cpp.o: In function `main':
InterfaceOpenMVG.cpp:(.text.startup.main+0x670): undefined reference to `openMVG::sfm::Load(openMVG::sfm::SfM_Data&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, openMVG::sfm::ESfM_Data)'
collect2: error: ld returned 1 exit status
apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG.dir/build.make:174: recipe for target 'bin/InterfaceOpenMVG' failed
make[2]: *** [bin/InterfaceOpenMVG] Error 1
CMakeFiles/Makefile2:370: recipe for target 'apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG.dir/all' failed
make[1]: *** [apps/InterfaceOpenMVG/CMakeFiles/InterfaceOpenMVG.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

Finally, I posted it only based on the tutorial you made. 

Have a good day,

Stephane

**Comment by pyp22** [comment] 2015-12-14 06:35
Hi Stephane,

Is openMVG-devel-v0.9 installed correctly ? Try also to compile & installe eigen & metis from here (not Arch ones). I remarked somehting while recompiling fron scratch on a fresh VM to try to repocude errors you meet.

Thanks & regards,

Pierre

**Comment by pyp22** [comment] 2015-12-14 06:47
A good thing i managed to reproduce the same error exactly. Got to debug that now. I'm not quite surprised. I had some difficulties to get my first binaries working. That's why i tagged openMVS in testing until i solved every compilation pb.

I will upload a working one on main packages repo (closed by now but tell you how to use it) So you'll be able to test it wihout waiting.

Regards

Pierre

**Comment by pyp22** [comment] 2015-12-14 12:05
Hi Stephane, here are the main repo infos. in /etc/pacman.conf add (end of file):

[nuxsfm]
SigLevel = Never
Server = http://repo1.nuxsfm.org/nuxsfm/os/$arch

Then do a pacman -Sy openMVS

Best regards,

PY

**Comment by stephane-lb** [comment] 2015-12-16 12:50
Hi Pierre-Yves,

I think this partial fix was not good ( or I should install the packages from this one ) 
I might do it in my new VM soon.

At the meantime, I made my first test and it was not successful at all, so might do lot of things wrong. Do you some ressource which explain the complet process ?

Just in case : 
- my dataset : vps.digital-lab.fr/sculture.tar.bz2 ( with the wrong spelling )
- my result : vps.digital-lab.fr/test.tar.bz2 

Kind regards,

Stephane

**Comment by pyp22** [comment] 2015-12-17 08:18
Hi Stephane, yes i saw that. There's a missing dep i'm trying to indentify. I will release new version of scripts ASAP. 
About you dataset, its due to your shoots. Particulary the diffuse light. Indoor shooting for photogramatry is  the hardest one as you need to have a good light handeling. For your fist try you may like to shoot an outdoor scene. My advices:

- Never use automatic mode. Use at least use the Aperture Priority mode. Manual is recommended.
- Depending on your lens, give priority to f/8 for lens like (17)24:70 mm. f/5.6 over 70mm. Keep f fixed. Always. On each serie of frame. (see below).
- Sensitivity: 100 ISO (max 400 i should say). Otherwise you get grains (that's your case. You shooted at 1600). That means amongst other things not enough info to describe the image.
- The scene: your way of shooting needs to be improved a bit, sorry :( Always try to have the whole subject full frame. In your case i would have shoot a serie of photos full frame, then a second one closer to your subject particulary on the most detailed part of the statue.

I'll write a short paper about that i need to improve and i'll post on NuxSFM wiki that might help other users too.

Best regards,

PY

**Comment by stephane-lb** [comment] 2015-12-17 10:38
Thank you Pierre-Yves, that's my first step in photogrammetry! Thank you so much for your answer and all the time you spent on NuxSFM.

Have a great day,

Stéphane

**Comment by pyp22** [comment] 2015-12-20 08:11
Hi Stephane,

Lastest commits should solve pb with openMVS. Reclone openMVG & openMVS and compile. Tried here on a fresh VM & done sudoing. I will update too the binary repo today.

Kindest regardPY

**Comment by stephane-lb** [comment] 2015-12-21 17:14
[ Test in progress ]

**Comment by pyp22** [comment] 2015-12-21 18:39
looking forward to see your first reconstruction ;) 
By the i'm finalizing a few scripts. But I already successfuly ran VisualSM on VM under XCFCE4 ^^

more to come :)

Regards

PY

**Comment by stephane-lb** [comment] 2015-12-21 19:36
Done ! Thank you so much Pierre-Yves ! ( vps.digital-lab.fr/dolphin.tar.bz2 )
I would never do that without your help. Let me know what you think about it ?

At the meantime, I saw that you add open to the repo, I suggest that you add the openni option to openCV too. And if you are interested, I started to write some PKGBUILD ( for Pangolin and ElasticFusion in my fork of your repository )

Kindest Regard,

Stéphane

**Comment by pyp22** [comment] 2015-12-22 08:15
Good job Stéphane! Always pleased to see some new results :) You might post it to G+ and poke #openMVG #openMVS #NuxSFM ^^ That will respectivly encourage Pierre Moulon & Dan too ;)

Your shooting is globaly good.I would have completed the scene shooting closer (or zooming a bit keeping f/8) 6 or 12 (multiple of 3 always)  photos to get the jaw for example. You might also try to tune both openMVG and openMVS parameters. See attached a quick run i've done this morning with your dataset. I used the Sift High describer preset. See https://openmvg.readthedocs.org/en/latest/software/SfM/ComputeFeatures You can also try other openMVG parameters of course. To find more points for example.

About openMVS. I'm not so familiar as I am with openMVG with it, but you can try to refine & remesh your results ti get a higher poly mesh. See 

1/ DensifyPointCloud scene.mvs (gives scen_dense.mvs)
2/ ReconstructMesh scene_dense.mvs
3/ TextureMesh scene_dense_mesh.mvs

If it does not suite you can first try to RefineMesh scene_mesh.mvs. See https://github.com/cdcseacave/openMVS/wiki/Usage (all parameters are not explained in the wiki. Use command line without option to get them). 

Both openCV & openNNI2 scripts are already available. Thanks also for Pangolin & ElasticFusion :+1: and congrats your first packaging. I have a few remark on it to help you. I'll post them on your git. I'm also preparing a short wiki for script writing with conventions & so on. 

Feel free to initialize a pull when its ready :)

Best regards,

PY




![snapshot00](https://cloud.githubusercontent.com/assets/8407357/11950377/24d7f208-a888-11e5-9443-2bd875f91710.png)

**Comment by pyp22** [comment] 2015-12-22 09:01
ubfortunatly issues are not activated on you GH. Anyway, here are some tricks & tips:

NuxSFM is using /usr/local (will explain whu in wiki) and works with splitted packages.

First split provides binaries, libraries and conf. This is for end users (not dev). It saves room too. This one might be under splitted too such as openMVG that mainly relies on command lines wihtout GUI. So installing a whole X11 server is not revelant. But it provides a UI (QT) tool too. That's why this one has its package what installs necessary deps (Xorg, a windowing system and so on ...)

Second split provides all header files and dev stuff (*.h, *.a, *.cmake, ...) they belong to the nuxsfm-devel group and are needed when developping is intended. A pacman -S base-devel nuxsfm-devel will install everything a dev or scriptor needs to compile. 

When splitting the add of a pkgbase varialble might be really helpful.

About your Pangolin/PKGBUILD. Nice first one by the way ;)
Unseeting CFAGS & CXXFLAGS is normaly not needed, except when meeting some compilation issues. If so, a useful thing to do is to add a options=('!debug' '!strip')

The make command. Giving the available amount of thread here is no useful. It's declared in /etc/makepkg.conf However, some (old) codes does not support MP. So a -j1 may be required. That's the exception.

Also don't forget to add a LICENSE function. Everything relying on licensing must be placed in ${pkgdir}/usr/share/licenses/${pkgname}

Don't forget to tell that YOU are the author of the script too ;)

More to come on wiki.

Best regards

PY

**Comment by pyp22** [comment] 2015-12-22 09:01
I'm closing this ticket and opening a new one on general dicussion.

**Closed by pyp22** 2015-12-22 09:01 UTC
Labels: bug

**Comment by stephane-lb** [comment] 2015-12-29 11:47
Oops forgot this message, I just opened the Bug tracker on my GH,

Hope to see you there ;-)

Stephane

**Comment by pyp22** [comment] 2015-12-30 05:31
Sure, already forked of course +1:

**Comment by stephane-lb** [comment] 2015-12-31 12:52
I applied some of your advices, but I am not sure I understand what you have in mind when you suggest to split the package ? Could we open a discuss, on my repo please ( to keep a little bit of consistency )

**Comment by pyp22** [comment] 2015-12-31 12:57
Yep, go ahead i follow you.
